algoritmo "Rendimento"
// Função :  Faça um algoritmo que receba um valor que foi depositado e exiba o
//valor com rendimento após um mês. Considere fixo o juro da poupança em 0,70% a. m.
// Autor :
// Data : 7/24/2019
// Seção de Declarações 
var
valor: real

inicio

ESCREVA("Informe o valor depositado: ")
LEIA(valor)

ESCREVAL("O valor do rendimento após um mês com taxa de 0,70 a.m. é ", valor * 1.007)

fimalgoritmo
